# Generated by Django 5.0.1 on 2024-01-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
