# Generated by Django 5.0.1 on 2024-01-26 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 26, 15, 41, 48, 777497)),
        ),
    ]
