# Generated by Django 5.0.1 on 2024-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
